-- AlterTable
ALTER TABLE "admin_audit" ALTER COLUMN "at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "backfill_progress" ALTER COLUMN "started_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "completed_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "checkouts" ALTER COLUMN "occurred_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "discord_members" ALTER COLUMN "joined_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "left_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "synced_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "item_aliases" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "items" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "pas_bills" ALTER COLUMN "paid_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "pas_runs" ALTER COLUMN "window_start" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "window_end" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "sent_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "payments" ALTER COLUMN "recorded_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "profiles" ALTER COLUMN "mapped_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "sessions" ALTER COLUMN "expires" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "testimonials" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "email_verified" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "first_login_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "last_login_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "verification_tokens" ALTER COLUMN "expires" SET DATA TYPE TIMESTAMPTZ(3);
