"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/db/client";
import { getAdHocProfiles, type AdHocProfileOption } from "@/db/queries/ad-hoc";
import { DeliveryStatus, PasRunStatus } from "@/generated/prisma/enums";
import { Prisma } from "@/generated/prisma/client";
import { coversSite, operatorId } from "@/lib/auth/admin-scope";
import { requireAnyAdmin } from "@/lib/auth/guard";
import {
  adHocDropLabel,
  adHocInstant,
  parseAdHocLines,
  parseDropDate,
  priceAdHocBill,
} from "@/lib/billing/ad-hoc";
import { payeeForSite, payeeLabel } from "@/lib/billing/payees";
import { isKnownSite, siteStyle, siteUsesProfiles } from "@/lib/sites";

/**
 * Issuing a fee by hand, for a retailer `/pas run` cannot see. See lib/billing/ad-hoc.ts.
 *
 * Every export calls `requireAnyAdmin()`, and every read is narrowed to the viewer's OWN
 * assigned profiles on retailers they run: a runner bills the members whose bot they run,
 * and a guessed profile id from anybody else's reads exactly like one that doesn't exist.
 *
 * WHO IS OWED is decided the way the bot decides it, by retailer: Premium Bandai to
 * peacemaker, Crunchyroll to chess, everything else to the operator -- not by who clicked.
 * A second Target runner issuing a Target fee is not owed it; the operator is, like every
 * other Target fee that night. See payeeForSite.
 *
 * NO DM. The bill lands on the member's dashboard like any other charge, and whoever issued
 * it tells them it's there. `delivery_status` says SKIPPED, `dm_text` stays null, and the
 * run is flagged `adHoc` so nothing mistakes it for a drop.
 */

export async function loadAdHocProfiles(siteKey: string): Promise<AdHocProfileOption[] | null> {
  const viewer = await requireAnyAdmin();
  if (!isKnownSite(siteKey) || !siteUsesProfiles(siteKey)) return null;
  if (!coversSite(viewer.adminSites, siteKey)) return null;
  return getAdHocProfiles(siteKey, viewer.discordUserId);
}

export type IssueResult =
  | {
      ok: true;
      billId: string;
      totalCents: number;
      memberName: string;
      /** "you", a payee's name, or "Okie ACO" -- for the confirmation line. */
      owedTo: string;
      /** True when this key had already been issued: a retry, not a second bill. */
      already: boolean;
    }
  | { ok: false; error: string };

const KEY = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export async function issueAdHocFee(form: FormData): Promise<IssueResult> {
  const viewer = await requireAnyAdmin();

  // Generated by the dialog when it opens. The run's sessionId is built from it and is
  // unique, so a double-click, a retry, or a slow network re-sending the POST all land on
  // the one bill instead of charging the member twice.
  const key = String(form.get("key") ?? "");
  if (!KEY.test(key)) return { ok: false, error: "Reload the page and try again." };
  const sessionId = `adhoc-${key.toLowerCase()}`;

  const siteKey = String(form.get("siteKey") ?? "");
  if (!isKnownSite(siteKey) || !siteUsesProfiles(siteKey)) {
    return { ok: false, error: "Pick a retailer." };
  }
  if (!coversSite(viewer.adminSites, siteKey)) return { ok: false, error: "Pick a retailer." };

  const already = await existingBill(sessionId, viewer.discordUserId);
  if (already) return already;

  const date = parseDropDate(String(form.get("date") ?? ""));
  if (!date) return { ok: false, error: "Pick the drop date — today or earlier." };

  const parsed = parseAdHocLines(
    form.getAll("product").map((product, i) => ({
      product: String(product),
      fee: String(form.getAll("fee")[i] ?? ""),
      qty: String(form.getAll("qty")[i] ?? ""),
    })),
  );
  if (!parsed.ok) return parsed;

  // Both predicates: the id from the form AND the viewer's own assignment. A profile that
  // is somebody else's is "not found", never "not yours".
  const profile = await prisma.vaultProfile.findFirst({
    where: {
      id: String(form.get("profileId") ?? ""),
      siteKey,
      account: { assigneeId: viewer.discordUserId },
    },
    select: {
      id: true,
      name: true,
      discordUserId: true,
      member: { select: { username: true, globalName: true, isOg: true } },
    },
  });
  if (!profile) return { ok: false, error: "Pick one of your profiles." };

  const payee = payeeForSite(siteKey);
  const payeeId = payee?.id ?? operatorId();
  if (!payeeId) return { ok: false, error: "No one to bill it to: ADMIN_DISCORD_IDS is empty." };

  // The operator's perk, so only on a fee owed to the operator. See priceAdHocBill.
  const discounted = payee === null && profile.member.isOg;
  const totals = priceAdHocBill(parsed.lines, discounted);

  // What the viewer reviewed must be what gets stored. The member's OG status can change
  // between the review and the click, and a bill that silently differs from the one on
  // screen is the kind nobody catches until the member asks.
  if (Number(form.get("reviewedTotal")) !== totals.totalCents) {
    return { ok: false, error: "The total changed since you reviewed it. Review it again." };
  }

  // Every line needs an item. A product nobody has billed before gets one, filed under this
  // retailer so the member's charge shows its chip; an existing item is never rewritten.
  const itemIds = new Map<string, string>();
  for (const line of parsed.lines) {
    const item = await prisma.item.upsert({
      where: { productKey: line.productKey },
      create: { productKey: line.productKey, label: line.label, source: siteKey },
      update: {},
      select: { id: true },
    });
    itemIds.set(line.productKey, item.id);
  }

  const dropLabel = adHocDropLabel(siteStyle(siteKey).label, date);
  const at = adHocInstant(date);

  let billId: string;
  try {
    billId = await prisma.$transaction(async (tx) => {
      const run = await tx.pasRun.create({
        data: {
          sessionId,
          windowStart: at,
          windowEnd: at,
          dropLabel,
          status: PasRunStatus.SENT,
          dryRun: false,
          operatorId: viewer.discordUserId,
          sentAt: new Date(),
          adHoc: true,
          bills: {
            create: {
              discordUserId: profile.discordUserId,
              payeeId,
              ...totals,
              ogApplied: discounted,
              // Nobody was DMed; the member finds it on their dashboard. See the header.
              deliveryStatus: DeliveryStatus.SKIPPED,
              lines: {
                create: parsed.lines.map((line) => ({
                  itemId: itemIds.get(line.productKey)!,
                  qty: line.qty,
                  feeCents: line.feeCents,
                  subtotalCents: line.subtotalCents,
                  label: line.label,
                })),
              },
            },
          },
        },
        select: { bills: { select: { id: true } } },
      });
      const id = run.bills[0].id;

      await tx.adminAudit.create({
        data: {
          actorDiscordId: viewer.discordUserId,
          action: "pas_bill.ad_hoc",
          entity: "pas_bill",
          entityId: id,
          after: {
            siteKey,
            dropLabel,
            profileId: profile.id,
            profileName: profile.name,
            memberId: profile.discordUserId,
            payeeId,
            ...totals,
            lines: parsed.lines.map(({ label, qty, feeCents }) => ({ label, qty, feeCents })),
          },
        },
      });
      return id;
    });
  } catch (error) {
    // Two clicks racing past the check above: the second hits the unique sessionId, and
    // the bill the first one created is the answer to both.
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      const raced = await existingBill(sessionId, viewer.discordUserId);
      if (raced) return raced;
    }
    console.error("billing: ad hoc fee failed", error instanceof Error ? error.message : "unknown");
    return { ok: false, error: "Couldn't issue that. Nothing was charged — try again." };
  }

  revalidatePath("/admin/charges");
  revalidatePath("/dashboard");
  return {
    ok: true,
    billId,
    totalCents: totals.totalCents,
    memberName: profile.member.globalName ?? profile.member.username,
    owedTo: payeeLabel(payeeId, viewer.discordUserId),
    already: false,
  };
}

/** The bill a key already produced, as a success -- or null when it hasn't produced one. */
async function existingBill(sessionId: string, viewerId: string): Promise<IssueResult | null> {
  const run = await prisma.pasRun.findUnique({
    where: { sessionId },
    select: {
      operatorId: true,
      bills: {
        take: 1,
        select: {
          id: true,
          totalCents: true,
          payeeId: true,
          member: { select: { username: true, globalName: true } },
        },
      },
    },
  });
  // Someone else's key is not a retry of yours -- say nothing about it.
  if (!run || run.operatorId !== viewerId || run.bills.length === 0) return null;
  const bill = run.bills[0];
  return {
    ok: true,
    billId: bill.id,
    totalCents: bill.totalCents,
    memberName: bill.member.globalName ?? bill.member.username,
    owedTo: payeeLabel(bill.payeeId, viewerId),
    already: true,
  };
}
